### ISSUE TITLE
Errors on php artisan key:generate

### ISSUE THREAD

**Issue by crishnakh** [control-the-work/control-the-work#16]
Hi, i'm having some erros trying to run php artisan key:generate

`PHP Fatal error:  Declaration of DateTime::modify(string $modifier) must be compatible with Carbon\CarbonInterface::modify($modify) in path/to/my/domain/vendor/nesbot/carbon/src/Carbon/Carbon.php on line 0
PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in path/to/my/domain/vendor/laravel/framework/src/Illuminate/Container/Container.php:851
Stack trace:
#0 path/to/my/domain/vendor/laravel/framework/src/Illuminate/Container/Container.php(851): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 path/to/my/domain/vendor/laravel/framework/src/Illuminate/Container/Container.php(818): Illuminate\Container\Container->resolveDependencies()
#2 path/to/my/domain/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build()
#3 path/to/my/domain/vendor/laravel/framework/src/Illuminate/Container/Container.php(265): Illuminate\Container\Container->resolve()
#4 path/to/my/domain/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Illuminate\Container\Container->Illuminate\Container\{closure}()
#5 path/to/my/domain/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build()
#6 path/to/my/domain/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve()
#7 path/to/my/domain/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\Container\Container->make()
#8 path/to/my/domain/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(159): Illuminate\Foundation\Application->make()
#9 path/to/my/domain/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(101): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#10 path/to/my/domain/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(87): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole()
#11 path/to/my/domain/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#12 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#13 {main}
  thrown in path/to/my/domain/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 851`

**Comment by crishnakh** [comment]
OK this problema was the php version running the command, but now i'm having troubles with "php artisan migrate --seed"
![Captura de pantalla 2021-02-02 a las 1 42 56](https://user-images.githubusercontent.com/3185290/106536108-009eb480-64f8-11eb-9248-76fd45958ba2.png)

**Comment by crishnakh** [comment]
Found the problems. I suggested some changes.
